apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: techchallenge
data:
  SERVER_PORT: "8081"
  SPRING_APPLICATION_NAME: "techchallange-order"

  CORS_ALLOWED_ORIGINS: "https://tech-challenge-front.vercel.app,http://localhost:5173"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "*"
  CORS_ALLOW_CREDENTIALS: "true"
  CORS_MAX_AGE: "3600"

  CUSTOMER_SERVICE_URL: "http://customer-service.techchallenge.svc.cluster.local:8080"

  JWT_ACCESS_TOKEN_EXPIRATION: "900000"
  JWT_REFRESH_TOKEN_EXPIRATION: "604800000"

  MERCADOPAGO_BASE_URL: "https://api.mercadopago.com"
  MERCADOPAGO_TIMEOUT: "30000"
  MERCADOPAGO_TEST_MODE: "false"
  MERCADOPAGO_INTEGRATION_ACTIVE: "true"