apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-order-service
  namespace: techchallenge
  labels:
    app: tech-challenge-order-service
spec:
  selector:
    app: tech-challenge-order-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP